[project]
name = "bunny-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "daphne==4.2.1",
    "django==6.0.2",
    "psycopg[binary,pool]==3.3.2",
    "whitenoise==6.11.0",
]
